# Generated by Django 3.2.9 on 2021-12-10 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_to_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
