version: '3.9'

services:
  frontend:
    build:
      context: ./client/
    ports:
      - 80:8080
  backend:
    build:
      context: ./server/
    ports:
      - 8000:8000
    volumes:
      - ./server/vuengo/static:/static
